export type RequestInvoiceDialogLabels = {
  close: string;
  loading: string;
  retry: string;
  loadError: string;
  customerLabel: string;
  requestNumberLabel: string;
  contractTypeLabel: string;
  tableIndex: string;
  tableDescription: string;
  tableAmount: string;
  title: string;
  platformName: string;
  platformSubtitle: string;
  printLabel: string;
  totalDueLabel: string;
  subtotalLabel: string;
  discountLabel: string;
  vatLabel: string;
  unpaidStatusLabel: string;
  paidStatusLabel: string;
};
